name: Create GitHub App

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the GitHub App'
        required: true
      organization:
        description: 'Organization to create the app in'
        required: true
      homepage_url:
        description: 'Homepage URL for the GitHub App'
        required: false
      permissions:
        description: 'Permissions for the GitHub App in JSON format'
        required: false
        default: '{"actions": "read", "pull_requests": "write"}'

jobs:
  create-github-app:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Manifest
        id: generate_manifest
        run: |
          homepage_url=${{ inputs.homepage_url || format('https://github.com/{0}/{1}', inputs.organization, inputs.app_name) }}
          manifest=$(jq -n \
            --arg name "${{ inputs.app_name }}" \
            --arg url "$homepage_url" \
            --arg redirect_url "https://github.com" \
            --arg hook_attributes_url "https://github.com" \
            --argjson permissions '${{ inputs.permissions }}' \
            '{
              "name": $name,
              "url": $url,
              "public": false,
              "redirect_url": $redirect_url,
              "hook_attributes": {
                "url": $hook_attributes_url
              },
              "default_permissions": $permissions
            }')
          echo "manifest=$(echo $manifest | jq -c . | sed 's/"/\\"/g')" >> $GITHUB_ENV

      - name: Generate Registration URL
        id: generate_url
        run: |
          encoded_manifest=$(echo -n ${{ env.manifest }} | jq -s -R -f /dev/stdin | sed 's/"//g')
          registration_url="https://github.com/organizations/${{ inputs.organization }}/settings/apps/new?manifest=$encoded_manifest"
          echo "url=$registration_url" >> $GITHUB_ENV

      - name: Display Registration URL
        run: |
          echo "Click the following URL to register your new GitHub App:"
          echo "${{ env.url }}"
